// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test, console} from "forge-std/Test.sol";
import {DepositVerifier} from "../src/verifiers/DepositVerifier.sol";
import {WithdrawVerifier} from "../src/verifiers/WithdrawVerifier.sol";
import {CollateralVerifier} from "../src/verifiers/CollateralVerifier.sol";

/*
 * Groth16 Verifier Tests
 *
 * Real Groth16 proofs generated by snarkjs from the ShieldLend circuits:
 *   - deposit.circom   (nullifier=123, secret=456, amount=1000)
 *   - withdraw.circom  (same note, 20-level tree, leaf at index 0)
 *   - collateral.circom (collateral=2000, borrowed=1000, ratio=15000)
 *
 * Proof values generated via scripts/gen_test_proofs.js using:
 *   - circuits/keys/*_final.zkey (main branch zkeys — NOT regenerated)
 *   - frontend/public/circuits/*.wasm
 *
 * Every test calls verifyProof with genuine BN128 curve points.
 * Anvil ships the BN128 precompiles (ecAdd, ecMul, ecPairing) so
 * the full pairing check runs in Foundry without any mocking.
 *
 * Unhappy paths:
 *   - `publicSignal_notInScalarField_*` — public input >= BN254 scalar field order `r`.
 *     The verifier's assembly `checkField` rejects these before pairing (Groth16 public
 *     inputs must lie in Fr). Forge coverage may still show 0% branch hit rate inside
 *     `assembly { ... }` because instrumentation does not map Yul branches to Solidity.
 */
contract Groth16VerifiersTest is Test {
    /// @dev Same constant as `r` in snarkJS-generated verifiers (BN254 scalar field order).
    uint256 internal constant BN254_SCALAR_FIELD_ORDER =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    DepositVerifier deposit;
    WithdrawVerifier withdraw;
    CollateralVerifier collateral;

    function setUp() public {
        deposit = new DepositVerifier();
        withdraw = new WithdrawVerifier();
        collateral = new CollateralVerifier();
    }

    // ═══════════════════════════════════════════════════════════════════════════
    //  DEPOSIT VERIFIER
    // ═══════════════════════════════════════════════════════════════════════════

    function test_deposit_validProof() public view {
        uint[2] memory pA = [
            0x1982e87ed762ea4c298a5c13384c9d4b0e03373207d96d27e3efa7477ad7cea5,
            0x1b253f1eac952bd5600d077bc75eabfa4769aabc38335f888998fe0695416257
        ];
        uint[2][2] memory pB = [
            [
                0x0bbcae762c9fa91659c2b2612a9c7d03c02215d1dc25428ace60ddb7470a2229,
                0x063f89ae60b369c5d284266e565a1d3d8396bbf19c2a3a69f5382beaf55bf541
            ],
            [
                0x074e8ea3a2e22602abfa662e28312d2bf49f6d7481b9cf39769db5c56d2ccb14,
                0x16d2c094c2bfcb1e9c9e36e18e4ad20b2307053848f1db3cac1b5d0123116664
            ]
        ];
        uint[2] memory pC = [
            0x1ae373309a90f46bb4e1132d9b398e069cfd9165eeb5f5dd094eb858f407925a,
            0x0fa85d233863722330cf5929aa5f13ff20122f5e4e758c0b574bf69942580fac
        ];
        // Public signals: [commitment, nullifierHash, amount]
        uint[3] memory pub = [
            0x179fedf5af8a0276d28600cc1cfd5324688dcd66029713234b6dab21500ed617,
            0x15e57b5244f1786e69d887cf6ebc5e2b25f3fc0b7520583029bc377982a66536,
            0x00000000000000000000000000000000000000000000000000000000000003e8
        ];

        assertTrue(deposit.verifyProof(pA, pB, pC, pub), "Valid deposit proof must verify");
    }

    function test_deposit_invalidProof_wrongPublicSignal() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _depositValidProofTuple();
        // Tampered amount: 9999 instead of 1000
        uint[3] memory pub = [
            0x179fedf5af8a0276d28600cc1cfd5324688dcd66029713234b6dab21500ed617,
            0x15e57b5244f1786e69d887cf6ebc5e2b25f3fc0b7520583029bc377982a66536,
            uint256(9999)
        ];

        assertFalse(deposit.verifyProof(pA, pB, pC, pub), "Tampered public signal must fail");
    }

    function test_deposit_invalidProof_zeroProof() public view {
        uint[2] memory pA = [uint256(1), uint256(2)]; // generator point G1
        uint[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint[2] memory pC = [uint256(1), uint256(2)];
        uint[3] memory pub = [uint256(0), uint256(0), uint256(0)];

        assertFalse(deposit.verifyProof(pA, pB, pC, pub), "Zero/dummy proof must fail");
    }

    function test_deposit_publicSignal_notInScalarField_slot0() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _depositValidProofTuple();
        uint[3] memory pub = _depositValidPub();
        pub[0] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(deposit.verifyProof(pA, pB, pC, pub), "pub[0] >= r must fail checkField");
    }

    function test_deposit_publicSignal_notInScalarField_slot1() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _depositValidProofTuple();
        uint[3] memory pub = _depositValidPub();
        pub[1] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(deposit.verifyProof(pA, pB, pC, pub), "pub[1] >= r must fail checkField");
    }

    function test_deposit_publicSignal_notInScalarField_slot2() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _depositValidProofTuple();
        uint[3] memory pub = _depositValidPub();
        pub[2] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(deposit.verifyProof(pA, pB, pC, pub), "pub[2] >= r must fail checkField");
    }

    function test_deposit_publicSignal_notInScalarField_aboveR() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _depositValidProofTuple();
        uint[3] memory pub = _depositValidPub();
        pub[0] = BN254_SCALAR_FIELD_ORDER + 1;
        assertFalse(deposit.verifyProof(pA, pB, pC, pub), "pub[0] > r must fail checkField");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    //  WITHDRAW VERIFIER
    // ═══════════════════════════════════════════════════════════════════════════

    function test_withdraw_validProof() public view {
        uint[2] memory pA = [
            0x0b656b6ce3c2ef325cd22b8971c1ae3e9cdd24c8c35799e93deaaf7ed6682b1c,
            0x2171a6f39977612a824aa15a929d7e0e6892d7e4eeacbe7c57b9be6925d1c535
        ];
        uint[2][2] memory pB = [
            [
                0x029dfda15dadd4bbe4db904b986791aa5aee9d8ec7aeae685eb7adc4d07d97ee,
                0x0e3eb5e1b5b64e77aed30b09d32a7872e209e36bcd0d0fa97b9abffa79802ee3
            ],
            [
                0x2b213a3c89442855609d946e26a88b5e26a0e3c8afc7e95f2335ea236c40380b,
                0x1ba001a19bd3fbfd7423d3525412929eb3feaa2859f07e4d1d2de864b8cc7637
            ]
        ];
        uint[2] memory pC = [
            0x19755972d00edc8ceafeb3583380ed3b8d973fff1b5a9f047540a3288d9a8676,
            0x1de07d72d23ffe88e4bb91a94a462a52d61ea880cc8cb7964bafad51ba661fa5
        ];
        // Public signals: [root, nullifierHash, recipient, amount]
        uint[4] memory pub = [
            0x27a838833c6fbb3b6b045366db4ab4fe9ab8345d4122937a4379d7dbd76a8bff,
            0x15e57b5244f1786e69d887cf6ebc5e2b25f3fc0b7520583029bc377982a66536,
            0x0000000000000000000000000000000000000000000000000000000000bc614e,
            0x00000000000000000000000000000000000000000000000000000000000003e8
        ];

        assertTrue(withdraw.verifyProof(pA, pB, pC, pub), "Valid withdraw proof must verify");
    }

    function test_withdraw_invalidProof_wrongRecipient() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _withdrawValidProofTuple();
        // Tampered recipient: 0xdead instead of 0xbc614e
        uint[4] memory pub = [
            0x27a838833c6fbb3b6b045366db4ab4fe9ab8345d4122937a4379d7dbd76a8bff,
            0x15e57b5244f1786e69d887cf6ebc5e2b25f3fc0b7520583029bc377982a66536,
            uint256(0xdead),
            0x00000000000000000000000000000000000000000000000000000000000003e8
        ];

        assertFalse(withdraw.verifyProof(pA, pB, pC, pub), "Tampered recipient must fail");
    }

    function test_withdraw_invalidProof_zeroProof() public view {
        uint[2] memory pA = [uint256(1), uint256(2)];
        uint[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint[2] memory pC = [uint256(1), uint256(2)];
        uint[4] memory pub = [uint256(0), uint256(0), uint256(0), uint256(0)];

        assertFalse(withdraw.verifyProof(pA, pB, pC, pub), "Zero/dummy proof must fail");
    }

    function test_withdraw_publicSignal_notInScalarField_slot0() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _withdrawValidProofTuple();
        uint[4] memory pub = _withdrawValidPub();
        pub[0] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(withdraw.verifyProof(pA, pB, pC, pub), "pub[0] >= r must fail checkField");
    }

    function test_withdraw_publicSignal_notInScalarField_slot1() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _withdrawValidProofTuple();
        uint[4] memory pub = _withdrawValidPub();
        pub[1] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(withdraw.verifyProof(pA, pB, pC, pub), "pub[1] >= r must fail checkField");
    }

    function test_withdraw_publicSignal_notInScalarField_slot2() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _withdrawValidProofTuple();
        uint[4] memory pub = _withdrawValidPub();
        pub[2] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(withdraw.verifyProof(pA, pB, pC, pub), "pub[2] >= r must fail checkField");
    }

    function test_withdraw_publicSignal_notInScalarField_slot3() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _withdrawValidProofTuple();
        uint[4] memory pub = _withdrawValidPub();
        pub[3] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(withdraw.verifyProof(pA, pB, pC, pub), "pub[3] >= r must fail checkField");
    }

    // ═══════════════════════════════════════════════════════════════════════════
    //  COLLATERAL VERIFIER
    // ═══════════════════════════════════════════════════════════════════════════

    function test_collateral_validProof() public view {
        uint[2] memory pA = [
            0x05b5ee78a3224fef898c4456205fbd20367e9bc826c385379718d7ad0bfb17fe,
            0x166175ab67f2548def6e64c29b236b9fabf4fd75c0b38010716b721def2b25f4
        ];
        uint[2][2] memory pB = [
            [
                0x08fc8c3bf987d3c450b6772d1cbdddd9ae02fffbff18df79b80d5eeec54af61e,
                0x21614d6cf0b6d501fb40e5badbb0ba633cb202bf23280c5772e4cee2813fd2d7
            ],
            [
                0x081ca76ab4fdf161675e10da8a212ef57389ce0870ef947b3da49de9d6b475f7,
                0x17a64e6a64e0b9cde685a3a6310f6bd670b8a19b070364469daef25f43a374cd
            ]
        ];
        uint[2] memory pC = [
            0x1dde7fcc0ba3ae48b95ea8163becf164be924853ec18ea9d52dc4178a6bc7e20,
            0x19ca6ed0a2f1c411531edf2d9fd33f7ded1198767012c0ee59a2f161a093f3f9
        ];
        // Public signals: [borrowed=1000, ratio=15000]
        uint[2] memory pub = [uint256(1000), uint256(15000)];

        assertTrue(collateral.verifyProof(pA, pB, pC, pub), "Valid collateral proof must verify");
    }

    function test_collateral_invalidProof_wrongBorrowed() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _collateralValidProofTuple();
        // Tampered borrowed: 5000 instead of 1000
        uint[2] memory pub = [uint256(5000), uint256(15000)];

        assertFalse(collateral.verifyProof(pA, pB, pC, pub), "Tampered borrowed amount must fail");
    }

    function test_collateral_invalidProof_zeroProof() public view {
        uint[2] memory pA = [uint256(1), uint256(2)];
        uint[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint[2] memory pC = [uint256(1), uint256(2)];
        uint[2] memory pub = [uint256(0), uint256(0)];

        assertFalse(collateral.verifyProof(pA, pB, pC, pub), "Zero/dummy proof must fail");
    }

    function test_collateral_publicSignal_notInScalarField_slot0() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _collateralValidProofTuple();
        uint[2] memory pub = [uint256(1000), uint256(15000)];
        pub[0] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(collateral.verifyProof(pA, pB, pC, pub), "pub[0] >= r must fail checkField");
    }

    function test_collateral_publicSignal_notInScalarField_slot1() public view {
        (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC) = _collateralValidProofTuple();
        uint[2] memory pub = [uint256(1000), uint256(15000)];
        pub[1] = BN254_SCALAR_FIELD_ORDER;
        assertFalse(collateral.verifyProof(pA, pB, pC, pub), "pub[1] >= r must fail checkField");
    }

    // ── Shared fixtures ───────────────────────────────────────────────────────

    function _depositValidProofTuple()
        internal
        pure
        returns (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC)
    {
        pA = [
            0x1982e87ed762ea4c298a5c13384c9d4b0e03373207d96d27e3efa7477ad7cea5,
            0x1b253f1eac952bd5600d077bc75eabfa4769aabc38335f888998fe0695416257
        ];
        pB = [
            [
                0x0bbcae762c9fa91659c2b2612a9c7d03c02215d1dc25428ace60ddb7470a2229,
                0x063f89ae60b369c5d284266e565a1d3d8396bbf19c2a3a69f5382beaf55bf541
            ],
            [
                0x074e8ea3a2e22602abfa662e28312d2bf49f6d7481b9cf39769db5c56d2ccb14,
                0x16d2c094c2bfcb1e9c9e36e18e4ad20b2307053848f1db3cac1b5d0123116664
            ]
        ];
        pC = [
            0x1ae373309a90f46bb4e1132d9b398e069cfd9165eeb5f5dd094eb858f407925a,
            0x0fa85d233863722330cf5929aa5f13ff20122f5e4e758c0b574bf69942580fac
        ];
    }

    function _depositValidPub() internal pure returns (uint[3] memory) {
        return [
            uint256(0x179fedf5af8a0276d28600cc1cfd5324688dcd66029713234b6dab21500ed617),
            uint256(0x15e57b5244f1786e69d887cf6ebc5e2b25f3fc0b7520583029bc377982a66536),
            uint256(1000)
        ];
    }

    function _withdrawValidProofTuple()
        internal
        pure
        returns (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC)
    {
        pA = [
            0x0b656b6ce3c2ef325cd22b8971c1ae3e9cdd24c8c35799e93deaaf7ed6682b1c,
            0x2171a6f39977612a824aa15a929d7e0e6892d7e4eeacbe7c57b9be6925d1c535
        ];
        pB = [
            [
                0x029dfda15dadd4bbe4db904b986791aa5aee9d8ec7aeae685eb7adc4d07d97ee,
                0x0e3eb5e1b5b64e77aed30b09d32a7872e209e36bcd0d0fa97b9abffa79802ee3
            ],
            [
                0x2b213a3c89442855609d946e26a88b5e26a0e3c8afc7e95f2335ea236c40380b,
                0x1ba001a19bd3fbfd7423d3525412929eb3feaa2859f07e4d1d2de864b8cc7637
            ]
        ];
        pC = [
            0x19755972d00edc8ceafeb3583380ed3b8d973fff1b5a9f047540a3288d9a8676,
            0x1de07d72d23ffe88e4bb91a94a462a52d61ea880cc8cb7964bafad51ba661fa5
        ];
    }

    function _withdrawValidPub() internal pure returns (uint[4] memory) {
        return [
            uint256(0x27a838833c6fbb3b6b045366db4ab4fe9ab8345d4122937a4379d7dbd76a8bff),
            uint256(0x15e57b5244f1786e69d887cf6ebc5e2b25f3fc0b7520583029bc377982a66536),
            uint256(0xbc614e),
            uint256(1000)
        ];
    }

    function _collateralValidProofTuple()
        internal
        pure
        returns (uint[2] memory pA, uint[2][2] memory pB, uint[2] memory pC)
    {
        pA = [
            0x05b5ee78a3224fef898c4456205fbd20367e9bc826c385379718d7ad0bfb17fe,
            0x166175ab67f2548def6e64c29b236b9fabf4fd75c0b38010716b721def2b25f4
        ];
        pB = [
            [
                0x08fc8c3bf987d3c450b6772d1cbdddd9ae02fffbff18df79b80d5eeec54af61e,
                0x21614d6cf0b6d501fb40e5badbb0ba633cb202bf23280c5772e4cee2813fd2d7
            ],
            [
                0x081ca76ab4fdf161675e10da8a212ef57389ce0870ef947b3da49de9d6b475f7,
                0x17a64e6a64e0b9cde685a3a6310f6bd670b8a19b070364469daef25f43a374cd
            ]
        ];
        pC = [
            0x1dde7fcc0ba3ae48b95ea8163becf164be924853ec18ea9d52dc4178a6bc7e20,
            0x19ca6ed0a2f1c411531edf2d9fd33f7ded1198767012c0ee59a2f161a093f3f9
        ];
    }
}
