// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test, console} from "forge-std/Test.sol";
import {LendingPool} from "../src/LendingPool.sol";
import {CollateralVerifier} from "../src/verifiers/CollateralVerifier.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";
import {ZkVerifyAggregation} from "../src/ZkVerifyAggregation.sol";

/*
 * LendingPool Tests
 *
 * Uses the real CollateralVerifier (BN128 precompiles available in Anvil).
 * Proof values generated by scripts/gen_test_proofs.js:
 *   collateral=2000, borrowed=1000, ratio=15000 (150%)
 *   2000*10000=20_000_000 >= 15000*1000=15_000_000 ✓
 *
 * Interest: 5% APY simple interest (INTEREST_RATE_BPS=500, BPS_DENOMINATOR=10000)
 * MIN_RATIO: 15000 (150% collateral)
 */
contract LendingPoolTest is Test {
    LendingPool pool;
    CollateralVerifier verifier;
    ShieldedPool shieldedPool;
    NullifierRegistry nullifierReg;
    ZkVerifyAggregation zkVerify;

    address deployer;
    address alice = makeAddr("alice");
    address bob   = makeAddr("bob");
    address carol = makeAddr("carol");

    // Real collateral proof: collateral=2000, borrowed=1000, ratio=15000
    uint256[2] PA_VALID = [
        0x05b5ee78a3224fef898c4456205fbd20367e9bc826c385379718d7ad0bfb17fe,
        0x166175ab67f2548def6e64c29b236b9fabf4fd75c0b38010716b721def2b25f4
    ];
    uint256[2][2] PB_VALID = [
        [
            0x08fc8c3bf987d3c450b6772d1cbdddd9ae02fffbff18df79b80d5eeec54af61e,
            0x21614d6cf0b6d501fb40e5badbb0ba633cb202bf23280c5772e4cee2813fd2d7
        ],
        [
            0x081ca76ab4fdf161675e10da8a212ef57389ce0870ef947b3da49de9d6b475f7,
            0x17a64e6a64e0b9cde685a3a6310f6bd670b8a19b070364469daef25f43a374cd
        ]
    ];
    uint256[2] PC_VALID = [
        0x1dde7fcc0ba3ae48b95ea8163becf164be924853ec18ea9d52dc4178a6bc7e20,
        0x19ca6ed0a2f1c411531edf2d9fd33f7ded1198767012c0ee59a2f161a093f3f9
    ];

    bytes32 constant NOTE_HASH_1 = bytes32(uint256(0xC0FFEE01));
    bytes32 constant NOTE_HASH_2 = bytes32(uint256(0xC0FFEE02));
    uint256 constant BORROWED = 1000;

    function setUp() public {
        deployer = address(this);
        verifier = new CollateralVerifier();
        zkVerify = new ZkVerifyAggregation(deployer);
        nullifierReg = new NullifierRegistry(address(0));
        pool = new LendingPool(
            address(shieldedPool),
            address(nullifierReg),
            address(verifier)
        );
        // Fund the pool so it can disburse loans
        vm.deal(address(pool), 100 ether);
        vm.deal(alice, 10 ether);
        vm.deal(bob, 10 ether);
        vm.deal(carol, 10 ether);
    }

    // ── Sanity: real proof verifies in CollateralVerifier ─────────────────────

    function test_collateralVerifier_validProof_verifies() public view {
        bool ok = verifier.verifyProof(PA_VALID, PB_VALID, PC_VALID, [BORROWED, uint256(15000)]);
        assertTrue(ok, "Real collateral proof should verify");
    }

    // ── borrow: happy path ────────────────────────────────────────────────────

    function test_borrow_disbursesFundsToRecipient() public {
        uint256 bobBefore = bob.balance;
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);
        assertEq(bob.balance, bobBefore + BORROWED);
    }

    function test_borrow_recordsLoanCorrectly() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        (
            bytes32 collHash,
            uint256 borrowed,
            uint256 interest,
            uint256 totalOwed,
            bool repaid
        ) = pool.getLoanDetails(0);

        assertEq(collHash, NOTE_HASH_1);
        assertEq(borrowed, BORROWED);
        assertEq(interest, 0); // no time elapsed
        assertEq(totalOwed, BORROWED);
        assertFalse(repaid);
    }

    function test_borrow_emitsEvent() public {
        vm.prank(alice);
        vm.expectEmit(true, true, false, true);
        emit LendingPool.Borrowed(0, NOTE_HASH_1, BORROWED, bob);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);
    }

    function test_borrow_incrementsLoanId() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);
        assertEq(pool.nextLoanId(), 1);

        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_2, BORROWED, payable(bob), 0);
        assertEq(pool.nextLoanId(), 2);
    }

    function test_borrow_marksNoteAsHavingActiveLoan() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);
        assertTrue(pool.hasActiveLoan(NOTE_HASH_1));
    }

    // ── borrow: unhappy paths ─────────────────────────────────────────────────

    function test_borrow_reverts_invalidProof_wrongBorrowed() public {
        // Proof was generated for borrowed=1000 but we pass 2000
        vm.prank(alice);
        vm.expectRevert(LendingPool.InvalidCollateralProof.selector);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, 2000, payable(bob), 0);
    }

    function test_borrow_reverts_zeroProof() public {
        uint256[2] memory pA = [uint256(1), uint256(2)];
        uint256[2][2] memory pB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint256[2] memory pC = [uint256(1), uint256(2)];

        vm.prank(alice);
        vm.expectRevert(LendingPool.InvalidCollateralProof.selector);
        pool.borrow(pA, pB, pC, NOTE_HASH_1, BORROWED, payable(bob), 0);
    }

    function test_borrow_reverts_noteAlreadyUsedAsCollateral() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(alice);
        vm.expectRevert(LendingPool.NoteAlreadyUsedAsCollateral.selector);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(carol), 0);
    }

    function test_borrow_reverts_borrowZeroAmount() public {
        // borrowed=0 → proof won't verify (proof was generated for borrowed=1000)
        vm.prank(alice);
        vm.expectRevert(LendingPool.InvalidCollateralProof.selector);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, 0, payable(bob), 0);
    }

    function test_borrow_differentNotesCanBorrowIndependently() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_2, BORROWED, payable(carol), 0);

        assertTrue(pool.hasActiveLoan(NOTE_HASH_1));
        assertTrue(pool.hasActiveLoan(NOTE_HASH_2));
        assertEq(pool.nextLoanId(), 2);
    }

    // ── interest accrual ──────────────────────────────────────────────────────

    function test_interest_zeroAtBorrowTime() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        (, , uint256 interest, , ) = pool.getLoanDetails(0);
        assertEq(interest, 0);
    }

    function test_interest_accruedAfterOneYear() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.warp(block.timestamp + 365 days);

        (, uint256 borrowed, uint256 interest, uint256 totalOwed, ) = pool.getLoanDetails(0);
        // 5% of BORROWED = 50 wei
        assertEq(interest, (borrowed * 500) / 10000);
        assertEq(totalOwed, borrowed + interest);
    }

    function test_interest_linearGrowth() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.warp(block.timestamp + 180 days);
        (, , uint256 interestHalf, , ) = pool.getLoanDetails(0);

        vm.warp(block.timestamp + 180 days); // total 360 days
        (, , uint256 interestFull, , ) = pool.getLoanDetails(0);

        // ~2x growth (slight rounding due to integer division)
        assertApproxEqAbs(interestFull, interestHalf * 2, 1);
    }

    // ── repay: happy path ─────────────────────────────────────────────────────

    function test_repay_exactPayment_closesLoan() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        (, , , uint256 totalOwed, ) = pool.getLoanDetails(0);

        vm.prank(bob);
        pool.repay{value: totalOwed}(0);

        (, , , , bool repaid) = pool.getLoanDetails(0);
        assertTrue(repaid);
    }

    function test_repay_unmarksActiveLoan() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(bob);
        pool.repay{value: BORROWED}(0);

        assertFalse(pool.hasActiveLoan(NOTE_HASH_1));
    }

    function test_repay_emitsEvent() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(bob);
        vm.expectEmit(true, false, false, true);
        emit LendingPool.Repaid(0, BORROWED);
        pool.repay{value: BORROWED}(0);
    }

    function test_repay_overpaymentRefunded() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        uint256 carolBefore = carol.balance;
        uint256 excess = 500;

        vm.prank(carol);
        pool.repay{value: BORROWED + excess}(0);

        // Carol should get back the excess
        assertEq(carol.balance, carolBefore - BORROWED);
    }

    function test_repay_anyoneCanRepayOnBehalf() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        // Carol repays alice's loan
        vm.prank(carol);
        pool.repay{value: BORROWED}(0);

        (, , , , bool repaid) = pool.getLoanDetails(0);
        assertTrue(repaid);
    }

    function test_repay_afterInterestAccrual() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.warp(block.timestamp + 365 days);

        (, , , uint256 totalOwed, ) = pool.getLoanDetails(0);
        assertTrue(totalOwed > BORROWED, "Should owe more than principal after 1 year");

        vm.prank(bob);
        pool.repay{value: totalOwed}(0);

        (, , , , bool repaid) = pool.getLoanDetails(0);
        assertTrue(repaid);
    }

    // ── repay: unhappy paths ──────────────────────────────────────────────────

    function test_repay_reverts_loanNotFound() public {
        vm.prank(alice);
        vm.expectRevert(LendingPool.LoanNotFound.selector);
        pool.repay{value: BORROWED}(999);
    }

    function test_repay_reverts_alreadyRepaid() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(bob);
        pool.repay{value: BORROWED}(0);

        vm.prank(bob);
        vm.expectRevert(LendingPool.LoanAlreadyRepaid.selector);
        pool.repay{value: BORROWED}(0);
    }

    function test_repay_reverts_underpayment() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(bob);
        vm.expectRevert(LendingPool.InsufficientRepayment.selector);
        pool.repay{value: BORROWED - 1}(0);
    }

    function test_repay_reverts_zeroPayment() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(bob);
        vm.expectRevert(LendingPool.InsufficientRepayment.selector);
        pool.repay{value: 0}(0);
    }

    function test_repay_afterRepay_noteCanBeUsedAsCollateralAgain() public {
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.prank(bob);
        pool.repay{value: BORROWED}(0);

        // After repayment, hasActiveLoan = false so we can borrow again
        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(carol), 0);

        assertTrue(pool.hasActiveLoan(NOTE_HASH_1));
        assertEq(pool.nextLoanId(), 2);
    }

    // ── fuzz tests ────────────────────────────────────────────────────────────

    function testFuzz_repay_overpaymentAlwaysRefunded(uint96 overpay) public {
        vm.assume(overpay > 0 && overpay < 10 ether);

        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.deal(carol, 100 ether); // ensure enough balance
        uint256 carolBefore = carol.balance;

        vm.prank(carol);
        pool.repay{value: BORROWED + uint256(overpay)}(0);

        // Carol sent (BORROWED + overpay) but gets overpay refunded → net loss = BORROWED
        assertEq(carol.balance, carolBefore - BORROWED);
    }

    function testFuzz_interest_neverExceedsPrincipalInFirstYear(uint40 elapsed) public {
        vm.assume(elapsed <= 365 days);

        vm.prank(alice);
        pool.borrow(PA_VALID, PB_VALID, PC_VALID, NOTE_HASH_1, BORROWED, payable(bob), 0);

        vm.warp(block.timestamp + elapsed);

        (, uint256 borrowed, uint256 interest, , ) = pool.getLoanDetails(0);
        // 5% APY — interest after 1 year = 5% of principal
        assertLe(interest, (borrowed * 500) / 10000, "Interest should not exceed 5% of principal in first year");
    }

    // ── view helpers ─────────────────────────────────────────────────────────

    function test_getLoanDetails_nonExistentLoan() public view {
        (bytes32 hash, uint256 borrowed, uint256 interest, uint256 total, bool repaid) =
            pool.getLoanDetails(999);
        assertEq(hash, bytes32(0));
        assertEq(borrowed, 0);
        assertEq(interest, 0);
        assertEq(total, 0);
        assertFalse(repaid);
    }

    function test_constants_areCorrect() public view {
        assertEq(pool.INTEREST_RATE_BPS(), 500);
        assertEq(pool.BPS_DENOMINATOR(), 10000);
        assertEq(pool.MIN_RATIO(), 15000);
    }
}
