// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";
import {LendingPool} from "../src/LendingPool.sol";

/*
 * ShieldLend Deployment Script
 *
 * Deployment order matters:
 *   1. Deploy NullifierRegistry (needs ShieldedPool address — use CREATE2 or deploy placeholder first)
 *   2. Deploy ShieldedPool (needs NullifierRegistry address + zkVerify attestation contract)
 *   3. Update NullifierRegistry to point to ShieldedPool (if using two-step deploy)
 *   4. Deploy Verifier contracts (generated by snarkjs setup.sh)
 *   5. Deploy LendingPool (needs ShieldedPool + NullifierRegistry + CollateralVerifier)
 *
 * Simplified approach used here:
 *   Deploy NullifierRegistry with address(0) first, then update via an initializer.
 *   In production: use CREATE2 to precompute addresses, or use an upgradeable proxy.
 *
 * Usage:
 *   # Local Anvil
 *   forge script contracts/script/Deploy.s.sol --rpc-url http://127.0.0.1:8545 --broadcast
 *
 *   # Base Sepolia testnet
 *   forge script contracts/script/Deploy.s.sol \
 *     --rpc-url $BASE_SEPOLIA_RPC_URL \
 *     --private-key $PRIVATE_KEY \
 *     --broadcast \
 *     --verify
 */
contract Deploy is Script {
    // zkVerify attestation contract on Base Sepolia
    // TODO: get the real address from https://docs.zkverify.io
    address constant ZKVERIFY_ATTESTATION_BASE_SEPOLIA = address(0); // placeholder

    // Collateral verifier is generated by: snarkjs zkey export solidityverifier
    // TODO: deploy CollateralVerifier.sol first, then set this address
    address constant COLLATERAL_VERIFIER = address(0); // placeholder (set after setup.sh)

    function run() external {
        uint256 deployerPrivateKey = vm.envOr("PRIVATE_KEY", uint256(0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80));
        address deployer = vm.addr(deployerPrivateKey);

        console.log("Deploying ShieldLend contracts...");
        console.log("Deployer:", deployer);
        console.log("Chain ID:", block.chainid);

        vm.startBroadcast(deployerPrivateKey);

        // 1. Deploy NullifierRegistry (temporarily with zero pool address)
        // In production: use CREATE2 or initializer pattern
        NullifierRegistry nullifierRegistry = new NullifierRegistry(address(0));
        console.log("NullifierRegistry deployed at:", address(nullifierRegistry));

        // 2. Deploy ShieldedPool
        ShieldedPool shieldedPool = new ShieldedPool(
            address(nullifierRegistry),
            ZKVERIFY_ATTESTATION_BASE_SEPOLIA
        );
        console.log("ShieldedPool deployed at:", address(shieldedPool));

        // Note: NullifierRegistry.shieldedPool is immutable — can't update.
        // TODO: redeploy NullifierRegistry with correct pool address.
        // For hackathon: use a mutable admin setter instead of immutable.

        // 3. Deploy LendingPool
        LendingPool lendingPool = new LendingPool(
            address(shieldedPool),
            address(nullifierRegistry),
            COLLATERAL_VERIFIER
        );
        console.log("LendingPool deployed at:", address(lendingPool));

        vm.stopBroadcast();

        // Print deployment summary
        console.log("\n=== ShieldLend Deployment Summary ===");
        console.log("Network:           ", _getNetworkName());
        console.log("NullifierRegistry: ", address(nullifierRegistry));
        console.log("ShieldedPool:      ", address(shieldedPool));
        console.log("LendingPool:       ", address(lendingPool));
        console.log("");
        console.log("Next steps:");
        console.log("1. Run scripts/setup.sh to generate circuit keys");
        console.log("2. Deploy verifier contracts (DepositVerifier, WithdrawVerifier, CollateralVerifier)");
        console.log("3. Redeploy NullifierRegistry with correct ShieldedPool address");
        console.log("4. Update COLLATERAL_VERIFIER in Deploy.s.sol with deployed verifier address");
        console.log("5. Configure zkVerify attestation contract address");
    }

    function _getNetworkName() internal view returns (string memory) {
        uint256 chainId = block.chainid;
        if (chainId == 1) return "Ethereum Mainnet";
        if (chainId == 11155111) return "Sepolia";
        if (chainId == 84532) return "Base Sepolia";
        if (chainId == 31337) return "Anvil (local)";
        return "Unknown";
    }
}
