// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script, console} from "forge-std/Script.sol";
import {NullifierRegistry} from "../src/NullifierRegistry.sol";
import {ShieldedPool} from "../src/ShieldedPool.sol";
import {LendingPool} from "../src/LendingPool.sol";
import {CollateralVerifier} from "../src/verifiers/CollateralVerifier.sol";

/*
 * ShieldLend Deployment Script
 *
 * Deployment order matters:
 *   1. Deploy NullifierRegistry (needs ShieldedPool address — use CREATE2 or deploy placeholder first)
 *   2. Deploy ShieldedPool (needs NullifierRegistry address + zkVerify attestation contract)
 *   3. Update NullifierRegistry to point to ShieldedPool (if using two-step deploy)
 *   4. Deploy Verifier contracts (generated by snarkjs setup.sh)
 *   5. Deploy LendingPool (needs ShieldedPool + NullifierRegistry + CollateralVerifier)
 *
 * Simplified approach used here:
 *   Deploy NullifierRegistry with address(0) first, then update via an initializer.
 *   In production: use CREATE2 to precompute addresses, or use an upgradeable proxy.
 *
 * Usage:
 *   # Local Anvil
 *   forge script contracts/script/Deploy.s.sol --rpc-url http://127.0.0.1:8545 --broadcast
 *
 *   # Base Sepolia testnet
 *   forge script contracts/script/Deploy.s.sol \
 *     --rpc-url $BASE_SEPOLIA_RPC_URL \
 *     --private-key $PRIVATE_KEY \
 *     --broadcast \
 *     --verify
 */
contract Deploy is Script {
    // zkVerify attestation contract on Base Sepolia
    // Get the real address from: https://docs.zkverify.io/overview/getting-started/contracts
    address constant ZKVERIFY_ATTESTATION_BASE_SEPOLIA = address(0); // TODO: set before mainnet deploy

    function run() external {
        uint256 deployerPrivateKey = vm.envOr("PRIVATE_KEY", uint256(0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80));
        address deployer = vm.addr(deployerPrivateKey);

        console.log("Deploying ShieldLend contracts...");
        console.log("Deployer:", deployer);
        console.log("Chain ID:", block.chainid);

        vm.startBroadcast(deployerPrivateKey);

        // 1. Deploy NullifierRegistry (temporarily with zero pool address)
        // In production: use CREATE2 or initializer pattern
        NullifierRegistry nullifierRegistry = new NullifierRegistry(address(0));
        console.log("NullifierRegistry deployed at:", address(nullifierRegistry));

        // 2. Deploy ShieldedPool
        ShieldedPool shieldedPool = new ShieldedPool(
            address(nullifierRegistry),
            ZKVERIFY_ATTESTATION_BASE_SEPOLIA
        );
        console.log("ShieldedPool deployed at:", address(shieldedPool));

        // 3. Deploy CollateralVerifier (generated by snarkjs from collateral.zkey)
        CollateralVerifier collateralVerifier = new CollateralVerifier();
        console.log("CollateralVerifier deployed at:", address(collateralVerifier));

        // 4. Deploy LendingPool
        LendingPool lendingPool = new LendingPool(
            address(shieldedPool),
            address(nullifierRegistry),
            address(collateralVerifier)
        );
        console.log("LendingPool deployed at:", address(lendingPool));

        vm.stopBroadcast();

        // Print deployment summary
        console.log("\n=== ShieldLend Deployment Summary ===");
        console.log("Network:            ", _getNetworkName());
        console.log("NullifierRegistry:  ", address(nullifierRegistry));
        console.log("ShieldedPool:       ", address(shieldedPool));
        console.log("CollateralVerifier: ", address(collateralVerifier));
        console.log("LendingPool:        ", address(lendingPool));
        console.log("");
        console.log("Next steps:");
        console.log("1. Set NEXT_PUBLIC_SHIELDED_POOL_ADDRESS and NEXT_PUBLIC_LENDING_POOL_ADDRESS in frontend/.env.local");
        console.log("2. Set ZKVERIFY_SEED_PHRASE in frontend/.env.local for proof submission");
    }

    function _getNetworkName() internal view returns (string memory) {
        uint256 chainId = block.chainid;
        if (chainId == 1) return "Ethereum Mainnet";
        if (chainId == 11155111) return "Sepolia";
        if (chainId == 84532) return "Base Sepolia";
        if (chainId == 31337) return "Anvil (local)";
        return "Unknown";
    }
}
