import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs";
import {
  createWalletClient,
  createPublicClient,
  http,
  parseAbi,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { baseSepolia } from "viem/chains";

// Server-side borrow flow (V2B):
//  1. Accept { proof, publicSignals, noteNullifierHash, borrowed, collateralAmount, recipient, collateralShard }
//  2. Submit collateral_ring Groth16 proof to zkVerify Volta → verified off-chain
//  3. Pick a random disburseShard ≠ collateralShard with sufficient ETH balance
//  4. Call LendingPool.borrow(noteNullifierHash, borrowed, collateralAmount, recipient, collateralShard, disburseShard)
//     — 6-param version: explicit cross-shard routing (collateral lock ≠ ETH disbursement shard)
//  5. Return { txHash, aggregationId }
//
// V2B vs V2A changes:
//   - Accept `collateralShard` from frontend (which shard holds the note)
//   - Random disburseShard selection: server reads all shard balances and picks
//     a funded shard that is DIFFERENT from collateralShard for privacy
//   - Call 6-param borrow() instead of 4-param (no _defaultShard fallback)
//   - recipient is now a stealth address generated by the frontend

const DOMAIN_ID = 0;

// All 5 V2B shard addresses (same as frontend .env.local)
const SHARD_ADDRESSES: `0x${string}`[] = ([
  process.env.NEXT_PUBLIC_SHARD_1,
  process.env.NEXT_PUBLIC_SHARD_2,
  process.env.NEXT_PUBLIC_SHARD_3,
  process.env.NEXT_PUBLIC_SHARD_4,
  process.env.NEXT_PUBLIC_SHARD_5,
].filter(Boolean) as string[]).map((a) => a as `0x${string}`);

// V2B LendingPool.borrow — 6-param with explicit shard routing
const LENDING_POOL_ABI = parseAbi([
  "function borrow(bytes32 noteNullifierHash, uint256 borrowed, uint256 collateralAmount, address recipient, address collateralShard, address disburseShard) external",
]);

// Pick a random shard (≠ collateralShard) that has at least `minBalance` ETH.
// Falls back to collateralShard itself if no other shard has enough liquidity.
async function pickDisburseShard(
  publicClient: ReturnType<typeof createPublicClient>,
  collateralShard: `0x${string}`,
  minBalance: bigint
): Promise<`0x${string}`> {
  const candidates = SHARD_ADDRESSES.filter(
    (s) => s.toLowerCase() !== collateralShard.toLowerCase()
  );

  // Shuffle candidates so we don't always pick Shard 2 when Shard 1 is collateral
  for (let i = candidates.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [candidates[i], candidates[j]] = [candidates[j], candidates[i]];
  }

  for (const shard of candidates) {
    const bal = await publicClient.getBalance({ address: shard });
    if (bal >= minBalance) return shard;
  }

  // All other shards lack liquidity — fall back to collateral shard
  console.warn("[borrow route] No cross-shard liquidity — falling back to collateralShard");
  return collateralShard;
}

export async function POST(req: NextRequest) {
  try {
    const {
      proof,
      publicSignals,
      noteNullifierHash,
      borrowed,
      collateralAmount,
      recipient,
      collateralShard,
    } = await req.json();

    if (
      !proof || !publicSignals || !noteNullifierHash ||
      !borrowed || !collateralAmount || !recipient || !collateralShard
    ) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const SEED_PHRASE = process.env.ZKVERIFY_SEED_PHRASE;
    if (!SEED_PHRASE) {
      return NextResponse.json({ error: "ZKVERIFY_SEED_PHRASE not set" }, { status: 500 });
    }

    const DEPLOYER_KEY = process.env.DEPLOYER_PRIVATE_KEY;
    const LENDING_POOL_ADDRESS = process.env.NEXT_PUBLIC_LENDING_POOL_ADDRESS as
      | `0x${string}`
      | undefined;

    if (!DEPLOYER_KEY || !LENDING_POOL_ADDRESS) {
      return NextResponse.json(
        { error: "DEPLOYER_PRIVATE_KEY or NEXT_PUBLIC_LENDING_POOL_ADDRESS not set" },
        { status: 500 }
      );
    }

    const { zkVerifySession, ZkVerifyEvents, Library, CurveType } = await import("zkverifyjs");

    const keysDir = path.join(process.cwd(), "..", "circuits", "keys");
    const vkey = JSON.parse(
      fs.readFileSync(path.join(keysDir, "collateral_ring_vkey.json"), "utf8")
    );

    const session = await zkVerifySession.start().Volta().withAccount(SEED_PHRASE);

    try {
      const { events, transactionResult } = await session
        .verify()
        .groth16({ library: Library.snarkjs, curve: CurveType.bn128 })
        .execute({ proofData: { vk: vkey, proof, publicSignals }, domainId: DOMAIN_ID });

      let aggregationId: number = 0;

      events.on(ZkVerifyEvents.IncludedInBlock, (eventData: { aggregationId: number }) => {
        if (eventData.aggregationId) aggregationId = eventData.aggregationId;
      });

      const result = await transactionResult;

      // zkVerify confirmed — select disburseShard and call LendingPool.borrow()
      const publicClient = createPublicClient({
        chain: baseSepolia,
        transport: http("https://sepolia.base.org"),
      });

      // Pick a funded shard different from where the collateral note lives
      const disburseShard = await pickDisburseShard(
        publicClient,
        collateralShard as `0x${string}`,
        BigInt(borrowed)
      );

      console.log(`[borrow route] collateralShard=${(collateralShard as string).slice(0, 10)} disburseShard=${disburseShard.slice(0, 10)}`);

      const account = privateKeyToAccount(DEPLOYER_KEY as `0x${string}`);
      const walletClient = createWalletClient({
        account,
        chain: baseSepolia,
        transport: http("https://sepolia.base.org"),
      });

      // 6-param borrow: collateralShard locks the nullifier, disburseShard pays ETH to recipient
      const txHash = await walletClient.writeContract({
        account,
        address: LENDING_POOL_ADDRESS,
        abi: LENDING_POOL_ABI,
        functionName: "borrow",
        args: [
          noteNullifierHash as `0x${string}`,
          BigInt(borrowed),
          BigInt(collateralAmount),
          recipient as `0x${string}`,
          collateralShard as `0x${string}`,
          disburseShard,
        ],
      });

      return NextResponse.json({ txHash, aggregationId, zkTxHash: result.txHash, disburseShard });
    } finally {
      await session.close();
    }
  } catch (err) {
    console.error("[borrow route]", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Unknown error" },
      { status: 500 }
    );
  }
}
