// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {ShieldedPool} from "./ShieldedPool.sol";
import {NullifierRegistry} from "./NullifierRegistry.sol";

/*
 * LendingPool — ShieldLend
 *
 * Enables borrowing against shielded deposits.
 * Loans are keyed to nullifierHash (not wallet address) — the borrower's
 * identity is unlinkable to their deposit address.
 *
 * Architecture:
 *   1. User has a note in ShieldedPool (private deposit of ETH as collateral)
 *   2. User generates a collateral.circom proof: "I have ≥ ratio% of borrowed"
 *   3. User calls borrow() — loan issued to ANY recipient address
 *   4. Loan tracked by noteNullifierHash (not address)
 *   5. Anyone can repay on behalf of a loan (flexible repayment)
 *   6. After repayment, user can withdraw ETH via ShieldedPool.withdraw()
 *
 * Revision note — Why key loans to nullifierHash:
 *   In standard Aave, loans are linked to msg.sender.
 *   In ShieldLend, we want the borrower's identity hidden.
 *   Using noteNullifierHash as the loan key:
 *     - Still uniquely identifies the collateral note
 *     - Does NOT reveal the depositor's address
 *     - Prevents the same note from being used as collateral twice
 *
 * Simplification in V1:
 *   - Collateral is ETH held in ShieldedPool
 *   - Loans are issued in ETH (same asset, for simplicity; USDC in V2)
 *   - Interest rate is fixed (dynamic rate model in V2)
 *   - No liquidation in V1 (oracle integration in V2)
 */

interface ICollateralVerifier {
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[2] calldata _pubSignals // [borrowed, ratio] — collateral.circom has nPublic=2
    ) external view returns (bool);
}

contract LendingPool {
    // ── State ─────────────────────────────────────────────────────────────────

    ShieldedPool public immutable shieldedPool;
    NullifierRegistry public immutable nullifierRegistry;
    ICollateralVerifier public immutable collateralVerifier; // auto-generated by snarkjs

    // Fixed interest rate: 5% per year, simplified as a constant for V1
    uint256 public constant INTEREST_RATE_BPS = 500; // 5%
    uint256 public constant BPS_DENOMINATOR = 10000;

    // Minimum collateral ratio: 150% (ratio = 15000 in collateral.circom)
    uint256 public constant MIN_RATIO = 15000;

    struct Loan {
        bytes32 collateralNullifierHash; // identifies the collateral note in ShieldedPool
        uint256 borrowed;               // amount borrowed
        uint256 timestamp;              // when the loan was taken
        address recipient;              // who received the loan funds
        bool repaid;
    }

    // loanId → Loan
    mapping(uint256 => Loan) public loans;
    uint256 public nextLoanId;

    // nullifierHash → active loanId (prevents same note being used twice)
    mapping(bytes32 => uint256) public activeLoanByNote;
    mapping(bytes32 => bool) public hasActiveLoan;

    // ── Events ────────────────────────────────────────────────────────────────
    event Borrowed(
        uint256 indexed loanId,
        bytes32 indexed collateralNullifierHash,
        uint256 amount,
        address recipient
    );
    event Repaid(uint256 indexed loanId, uint256 totalRepaid);

    // ── Errors ────────────────────────────────────────────────────────────────
    error InvalidCollateralProof();
    error InsufficientRatio();
    error NoteAlreadyUsedAsCollateral();
    error LoanNotFound();
    error LoanAlreadyRepaid();
    error InsufficientRepayment();

    constructor(
        address _shieldedPool,
        address _nullifierRegistry,
        address _collateralVerifier
    ) {
        shieldedPool = ShieldedPool(_shieldedPool);
        nullifierRegistry = NullifierRegistry(_nullifierRegistry);
        collateralVerifier = ICollateralVerifier(_collateralVerifier);
    }

    // ── Core: Borrow ──────────────────────────────────────────────────────────
    /*
     * Borrow against a shielded collateral note.
     *
     * @param collateralProof       Groth16 proof from collateral.circom
     * @param noteNullifierHash     Poseidon(noteNullifier) — identifies the collateral note
     * @param borrowed              Amount to borrow (in wei)
     * @param recipient             Address to receive the borrowed funds
     * @param zkVerifyAttestationId zkVerify attestation covering the collateral proof
     */
    function borrow(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        bytes32 noteNullifierHash,
        uint256 borrowed,
        address payable recipient,
        uint256 zkVerifyAttestationId
    ) external {
        // 1. Prevent same collateral note being used twice
        if (hasActiveLoan[noteNullifierHash]) revert NoteAlreadyUsedAsCollateral();

        // 2. Verify the collateral proof via collateral verifier contract
        // Public signals: [borrowed, MIN_RATIO]
        // collateral.circom has nPublic=2: borrowed and ratio are public inputs.
        // The range constraint (collateral >= ratio/10000 * borrowed) is enforced internally.
        uint256[2] memory pubSignals = [borrowed, MIN_RATIO];
        if (!collateralVerifier.verifyProof(pA, pB, pC, pubSignals)) {
            revert InvalidCollateralProof();
        }

        // 3. Register the loan
        uint256 loanId = nextLoanId++;
        loans[loanId] = Loan({
            collateralNullifierHash: noteNullifierHash,
            borrowed: borrowed,
            timestamp: block.timestamp,
            recipient: recipient,
            repaid: false
        });
        activeLoanByNote[noteNullifierHash] = loanId;
        hasActiveLoan[noteNullifierHash] = true;

        // 4. Disburse loan
        (bool success, ) = recipient.call{value: borrowed}("");
        require(success, "Disbursement failed");

        emit Borrowed(loanId, noteNullifierHash, borrowed, recipient);
    }

    // ── Core: Repay ───────────────────────────────────────────────────────────
    /*
     * Repay a loan. Anyone can repay on behalf of anyone else.
     * Full repayment required in V1 (partial repayment in V2).
     */
    function repay(uint256 loanId) external payable {
        Loan storage loan = loans[loanId];
        if (loan.borrowed == 0) revert LoanNotFound();
        if (loan.repaid) revert LoanAlreadyRepaid();

        uint256 interest = _calculateInterest(loan.borrowed, loan.timestamp);
        uint256 totalOwed = loan.borrowed + interest;

        if (msg.value < totalOwed) revert InsufficientRepayment();

        loan.repaid = true;
        hasActiveLoan[loan.collateralNullifierHash] = false;

        // Return excess payment
        if (msg.value > totalOwed) {
            (bool ok, ) = msg.sender.call{value: msg.value - totalOwed}("");
            require(ok, "Refund failed");
        }

        emit Repaid(loanId, totalOwed);
    }

    // ── View: Loan details ────────────────────────────────────────────────────
    function getLoanDetails(uint256 loanId)
        external
        view
        returns (
            bytes32 collateralNullifierHash,
            uint256 borrowed,
            uint256 currentInterest,
            uint256 totalOwed,
            bool repaid
        )
    {
        Loan storage loan = loans[loanId];
        uint256 interest = _calculateInterest(loan.borrowed, loan.timestamp);
        return (
            loan.collateralNullifierHash,
            loan.borrowed,
            interest,
            loan.borrowed + interest,
            loan.repaid
        );
    }

    // ── Internal: Simple fixed-rate interest ─────────────────────────────────
    function _calculateInterest(uint256 principal, uint256 startTime)
        internal
        view
        returns (uint256)
    {
        uint256 elapsed = block.timestamp - startTime;
        // Simple interest: principal * rate * time / (365 days * BPS_DENOMINATOR)
        return (principal * INTEREST_RATE_BPS * elapsed) / (365 days * BPS_DENOMINATOR);
    }

    // ── Receive ETH (for pool funding) ───────────────────────────────────────
    receive() external payable {}
}
